export const LIST_CARTS = 'LIST_CARTS';
export const GET_NUMBER_CART = 'GET_NUMBER_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_EMPTY = 'CART_EMPTY';
